# Tweak large thresholds/limits for embedded targets
array-size-threshold = 1024   # from 16384
future-size-threshold = 1024  # from 16384
pass-by-value-size-limit = 32 # from 256
stack-size-threshold = 4096   # from 512000
vec-box-size-threshold = 512  # from 4096
